name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  url_launcher: ^6.3.1
  flutter_animate: ^4.5.2
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pfp.png
    - assets/images/fb.png
    - assets/images/github.png
    - assets/images/startup.jpg
    - assets/images/icebox.jpg
    - assets/images/tracking.jpg
    - assets/images/analytics.jpg
    - assets/images/tascadia-dash.jpg
    - assets/images/tascadia-login.jpg
    - assets/images/logo.png
    - assets/images/favicon-32x32.png
    - assets/images/oro_home.png
    - assets/images/oro_items.png